### ISSUE TITLE
error：no matching function for call to 'obx::Box<Task>::put(<brace-enclosed initializer list>)

### ISSUE THREAD

**Issue by Laganer** [objectbox/objectbox-c#7]
when I  compile the example by running: g++ main.cpp -I. -std=c++11 -lobjectbox
error：no matching function for call to 'obx::Box<Task>::put(<brace-enclosed initializer list>)

obx_id id = box.put({.text = "Buy milk"})
                                                               ^

int main()
{
    obx::Store store(create_obx_model());
    obx::Box<Task> box(store);

    obx_id id = box.put({.text = "Buy milk"});  //  error code

   std::unique_ptr<Task> task = box.get(id);   // Read
    if (task) {
        task->text += " & some bread";
        box.put(*task);                         // Update
        box.remove(id);                         // Delete
    }
    return 0;
}

**Comment by vaind** [comment]
I've just tested the example you're probably referring to  (https://cpp.objectbox.io/getting-started) and it worked for me - I've got no error.

Could you maybe zip the whole directory you've tried this in and attach it to the issue? So I can try to run the exact same code?
Also, what platform and compiler are you using? `uname -a` and `g++ --version`

**Comment by Laganer** [comment]
Thanks for your reply !




 
I've just tested the example you're probably referring to  (https://cpp.objectbox.io/getting-started) and it worked for me - I've got no error.
 
Could you maybe zip the whole directory you've tried this in and attach it to the issue? So I can try to run the exact same code?
 Also, what platform and compiler are you using? uname -a and g++ --version

**Comment by vaind** [comment]
Looks like the getting-started page answered the questions. Feel free to follow-up in case there's still an issue.
